[project]
name = "aisuite-hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aisuite[ollama]>=0.1.11",
    "docstring-parser>=0.16",
    "ipykernel>=6.29.5",
]
